spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: root
    password: admin
    driverClassName: org.postgresql.Driver
